### ISSUE TITLE
Consume/Purchase

### ISSUE THREAD

**Issue by Gonozal398** [Forceu/barcodebuddy-docker#7] opened 2020-05-02 18:42 UTC
Thanks for the great job you did.
I'm using Grocy and Barcode Buddy as docker in the latest version
In Grocy, for example, I can set barcode "123456" purchase 1 package corresponds to 6 pieces in consumption.
If I enter the code 123456 in Grocy as purchase, it also counts 6 pieces in the stock.
If I enter 123456 as consumption, it reduces 1 piece in Stock

If I scan the code as a purchase with Barcodebuddy then it counts only 1 piece but not 6 pieces as it should be.

**Comment by Forceu** [comment] 2020-05-03 13:34
Duplicate of https://github.com/Forceu/barcodebuddy/issues/37

You can use the Quantity barcode (eg. BBUDDY-Q-6) after scanning the barcode 123456 to set the amount of items to 6. Also in the settings menu you can enable the option to respect this value for consuming. I will add an option later on to respect grocy's QU_Factor.

**Closed by Forceu** 2020-05-03 13:34 UTC
